# Python CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    docker:
        - image: circleci/python:3.6.9

    working_directory: ~/MERlin

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: Install Dependencies
          command: |
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
            source ~/miniconda/bin/activate root
            conda activate base
            conda config --set always_yes true
            conda config --set quiet true
            conda create -n merlin_env python=3.6
            source activate merlin_env
            conda install rtree
            conda install pytables
            conda install statsmodels numba
            conda install -c conda-forge python-igraph louvain
            cd ~
            printf 'DATA_HOME=~\nANALYSIS_HOME=~\nPARAMETERS_HOME=~\n' >.merlinenv
            pip install -e MERlin
            cd ~/MERlin
      # Step 3: run linter and tests
      - run:
          name: Run Tests
          command: |
            source ~/miniconda/bin/activate root
            conda activate base
            source activate merlin_env
            cd ~/MERlin
            mkdir ~/test-reports
            pytest --cov --cov-report=xml

      - run:
          name: Upload Coverage to Codecov
          command: |
              source ~/miniconda/bin/activate root
              cd ~/MERlin
              pip install codecov && codecov 
      - store_artifacts:
          path: ~/MERlin/coverage.xml
